// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/home/Banner.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    CheckboxElement: typeof import('./src/components/forms/CheckboxElement.vue')['default']
    DiscountCard: typeof import('./src/components/home/DiscountCard.vue')['default']
    Discounts: typeof import('./src/components/home/Discounts.vue')['default']
    FlightCard: typeof import('./src/components/booking/flights/FlightCard.vue')['default']
    FlightList: typeof import('./src/components/booking/flights/FlightList.vue')['default']
    FlightSummary: typeof import('./src/components/booking/summary/FlightSummary.vue')['default']
    InputElement: typeof import('./src/components/forms/InputElement.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/forms/login/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar.vue')['default']
    OrderSummary: typeof import('./src/components/booking/summary/OrderSummary.vue')['default']
    PartnerItem: typeof import('./src/components/home/PartnerItem.vue')['default']
    Partners: typeof import('./src/components/home/Partners.vue')['default']
    PassengerForm: typeof import('./src/components/forms/booking/PassengerForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RegistrationForm: typeof import('./src/components/forms/register/RegistrationForm.vue')['default']
    RouterButton: typeof import('./src/components/common/RouterButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterText: typeof import('./src/components/common/RouterText.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFlightsForm: typeof import('./src/components/forms/booking/SearchFlightsForm.vue')['default']
    SeatForm: typeof import('./src/components/forms/booking/SeatForm.vue')['default']
    StepButtons: typeof import('./src/components/forms/booking/StepButtons.vue')['default']
    Steps: typeof import('primevue/steps')['default']
    Ticket: typeof import('./src/components/home/Ticket.vue')['default']
    Tickets: typeof import('./src/components/home/Tickets.vue')['default']
    TicketsSummary: typeof import('./src/components/booking/summary/TicketsSummary.vue')['default']
  }
}

export {}
